### ISSUE TITLE
Error after deleting row

### ISSUE THREAD

**Issue by amcorch** [jcustenborder/kafka-connect-cdc-mssql#23]
Connector is working fine for inserts and updates, however if I delete a row from a tracked table I get the following error.

[2018-04-13 15:12:01,280] ERROR Exception thrown while querying for ChangeKey{databaseName=Galaxy7, schemaName=dbo, tableName=GxEventStore} (com.github.jcustenborder.kafka.connect.cdc.mssql.QueryService),
java.lang.NullPointerException,
	at com.github.jcustenborder.kafka.connect.cdc.mssql.MsSqlChange$Builder.build(MsSqlChange.java:222),
	at com.github.jcustenborder.kafka.connect.cdc.mssql.QueryService.queryTable(QueryService.java:129),
	at com.github.jcustenborder.kafka.connect.cdc.mssql.QueryService.processTables(QueryService.java:92),
	at com.github.jcustenborder.kafka.connect.cdc.mssql.QueryService.run(QueryService.java:67),
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60),
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:95),
	at java.lang.Thread.run(Thread.java:745)

Is there any configuration I might be missing?

**Comment by badihi** [comment]
Same thing here. Any solutions?

**Comment by thangbn** [comment]
this caused missing null check, created a PR to fix it #29
