### ISSUE TITLE
com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near '='

### ISSUE THREAD

**Issue by anandrajneesh** [jcustenborder/kafka-connect-cdc-mssql#27]
While running the connector I am getting following exception. From the logs I can see that the schema name, database name and table name are correct. Can you please tell me what I am missing here ?
```
[2018-04-27 16:28:42,262] ERROR Exception thrown while querying for ChangeKey{databaseName=PAG, schemaName=dbo, tableName=customer} (com.github.jcustenborder.kafk
a.connect.cdc.mssql.QueryService)
org.apache.kafka.connect.errors.DataException: Exception thrown while getting metadata for ChangeKey{databaseName=IKB, schemaName=dbo, tableName=ix_spc_planogram}
        at com.github.jcustenborder.kafka.connect.cdc.CachingTableMetadataProvider.tableMetadata(CachingTableMetadataProvider.java:64)
        at com.github.jcustenborder.kafka.connect.cdc.mssql.QueryService.queryTable(QueryService.java:108)
        at com.github.jcustenborder.kafka.connect.cdc.mssql.QueryService.processTables(QueryService.java:92)
        at com.github.jcustenborder.kafka.connect.cdc.mssql.QueryService.run(QueryService.java:67)
        at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60)
        at com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near '='.
        at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
        at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
        at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:137)
        at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2348)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2320)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4739)
        at com.github.jcustenborder.kafka.connect.cdc.CachingTableMetadataProvider.tableMetadata(CachingTableMetadataProvider.java:56)
        ... 6 more
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near '='.
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:259)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1547)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:548)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:479)
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7344)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2713)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:224)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:204)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:401)
        at com.github.jcustenborder.kafka.connect.cdc.mssql.MsSqlTableMetadataProvider.fetchTableMetadata(MsSqlTableMetadataProvider.java:96)
        at com.github.jcustenborder.kafka.connect.cdc.CachingTableMetadataProvider$1.call(CachingTableMetadataProvider.java:59)
        at com.github.jcustenborder.kafka.connect.cdc.CachingTableMetadataProvider$1.call(CachingTableMetadataProvider.java:56)
        at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4742)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
        ... 11 more
```

Below is the configuration file : 
```
name=mssqlsource
tasks.max=1
connector.class=com.github.jcustenborder.kafka.connect.cdc.mssql.MsSqlSourceConnector
initial.database=PAG
server.name=localhost
server.port=1433
username=foo
password=bar
change.tracking.tables=dbo.customer
```

**Comment by anandrajneesh** [comment]
So the query is using a expression `iif` which is supported from SQL Server 2012 onwards and my version is 2008. I guess this connector won't support SQLServer 2008.
