### ISSUE TITLE
Exception when executing debug.sh

### ISSUE THREAD

**Issue by alighanem** [jcustenborder/kafka-connect-cdc-mssql#4]
Hello,

I deployed a docker stack with kafka, zookeeper and schema-registry.
After updating the properties file, I executed the debug.sh file. It has generated jar packages.
I had to update the debug.sh file to specify the path to the connect-standalone script file and I executed it but I got this message : 
INFO Added alias 'ValueToKey' to plugin 'org.apache.kafka.connect.transforms.ValueToKey' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:290)
Exception in thread "main" org.apache.kafka.common.config.ConfigException: Invalid value io.confluent.connect.avro.AvroConverter for configuration key.converter: Class io.confluent.connect.avro.AvroConverter could not be found.
    at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:715)
    at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:460)
    at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:453)
    at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:62)
    at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:75)
    at org.apache.kafka.connect.runtime.WorkerConfig.<init>(WorkerConfig.java:197)
    at org.apache.kafka.connect.runtime.standalone.StandaloneConfig.<init>(StandaloneConfig.java:42)
    at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:70)

Can you help me? I do not understand this message. And I am wondering what I have to do with the jar packages generated?

Thank you in advance for your help,

Ali

**Comment by jcustenborder** [comment]
@alighanem I would suggest reading [this first](https://docs.confluent.io/current/connect/userguide.html#installing-plugins). The script that you executed is used to for debugging. If you want to use this connector you can run `mvn clean package` which will generate a tar.gz with all of the files needed to run. Make sure you follow the installation guide to get the [jar for sql server installed](https://github.com/jcustenborder/kafka-connect-cdc-mssql#installation).
