### ISSUE TITLE
What's `sourceOffset`? 

### ISSUE THREAD

**Issue by letusfly85** [jcustenborder/kafka-connect-cdc-mssql#5]
Hi, I'm trying to use this connector on my local machine with confluent-3.3.0.

After I load mssqlsource, I got error below.
What's `sourceOffset`? , and How can I set this property?

```
[2017-11-09 13:36:05,564] ERROR Exception thrown while querying for ChangeKey{databaseName=cdc_testing, schemaName=dbo, tableName=employee} (com.github.jcustenborder.kafka.connect.cdc.mssql.QueryService:94)
java.lang.NullPointerException: sourceOffset cannot be null.
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787)
	at com.github.jcustenborder.kafka.connect.cdc.mssql.MsSqlChange.offset(MsSqlChange.java:61)
	at com.github.jcustenborder.kafka.connect.cdc.mssql.QueryService.queryTable(QueryService.java:113)
	at com.github.jcustenborder.kafka.connect.cdc.mssql.QueryService.processTables(QueryService.java:92)
	at com.github.jcustenborder.kafka.connect.cdc.mssql.QueryService.run(QueryService.java:67)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
	at java.lang.Thread.run(Thread.java:748)
```

My configuration file is below. Thank you.

```
name=mssqlsource
tasks.max=2
connector.class=com.github.jcustenborder.kafka.connect.cdc.mssql.MsSqlSourceConnector
initial.database=cdc_testing
change.tracking.tables=dbo.employee
server.name=0.0.0.0
server.port=1443
username=sa
password=*****
topic=cdc-testing
```

**Comment by letusfly85** [comment]
Sorry, I misunderstood about `sys.change_tracking_tables`.
