### ISSUE TITLE
Error while deploying Source Connector

### ISSUE THREAD

**Issue by nehabhardwaj01** [jcustenborder/kafka-connect-cdc-mssql#6]
Following are the error logs of kafka-connect while deploying a MSSQL source connector-
[2017-12-21 13:30:48,400] INFO Starting Services (com.github.jcustenborder.kafka.connect.cdc.BaseServiceTask:44)
[2017-12-21 13:30:48,406] INFO Source task WorkerSourceTask{id=mssql-connector-0} finished initialization and start (org.apache.kafka.connect.runtime.WorkerSourceTask:143)
Dec 21, 2017 1:30:48 PM com.google.common.util.concurrent.ServiceManager$ServiceListener failed
SEVERE: Service QueryService [FAILED] has failed in the RUNNING state.
java.lang.NoClassDefFoundError: com/microsoft/sqlserver/jdbc/SQLServerConnectionPoolDataSource
	at com.github.jcustenborder.kafka.connect.cdc.mssql.MsSqlConnectionPoolDataSourceFactory.connectionPool(MsSqlConnectionPoolDataSourceFactory.java:36)
	at com.github.jcustenborder.kafka.connect.cdc.JdbcUtils.lambda$openPooledConnection$0(JdbcUtils.java:51)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at com.github.jcustenborder.kafka.connect.cdc.JdbcUtils.openPooledConnection(JdbcUtils.java:48)
	at com.github.jcustenborder.kafka.connect.cdc.mssql.QueryService.queryTable(QueryService.java:103)
	at com.github.jcustenborder.kafka.connect.cdc.mssql.QueryService.processTables(QueryService.java:92)
	at com.github.jcustenborder.kafka.connect.cdc.mssql.QueryService.run(QueryService.java:67)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
	at java.lang.Thread.run(Thread.java:748)

**Comment by jcustenborder** [comment]
I cannot distribute the JDBC connector. Take a look at this part of the [documentation](https://github.com/jcustenborder/kafka-connect-cdc-mssql#installation).
